apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/api-replicas.yaml
    target:
      kind: Deployment
      name: api-gateway
  - path: patches/auth-replicas.yaml
    target:
      kind: Deployment
      name: app-auth
  - path: patches/user-replicas.yaml
    target:
      kind: Deployment
      name: app-user
  - path: patches/order-replicas.yaml
    target:
      kind: Deployment
      name: app-order
  - path: patches/payment-replicas.yaml
    target:
      kind: Deployment
      name: app-payment