apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-order
  labels:
    app: app-order
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-order
  template:
    metadata:
      name: app-order
      labels:
        app: app-order
    spec:
      containers:
        - name: app-order
          image: voodz/orderservice:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: system-config
            - secretRef:
                name: system-secrets
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: system-config
                  key: SPRING_DATASOURCE_URL_ORDERSERVICE
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: system-secrets
                  key: DB_USER
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: system-secrets
                  key: DB_PASSWORD
            - name: USERSERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: system-config
                  key: USER_SERVICE_URL
          ports:
            - containerPort: 8083
          livenessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8083
            initialDelaySeconds: 10
            periodSeconds: 5