services:
  gateway:
    build:
      context: ./ApiGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      USER_SERVICE_URL: ${USER_SERVICE_URL}
      AUTH_SERVICE_URL: ${AUTH_SERVICE_URL}
      ORDER_SERVICE_URL: ${ORDER_SERVICE_URL}

  userservice:
    build:
      context: ./UserService
      dockerfile: Dockerfile
    container_name: userservice-app
    ports:
      - "8081:8081"
    depends_on:
      - userservice-postgres
      - redis
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://userservice-postgres:5432/${DB_USER_SERVICE}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}

  authservice:
    build:
      context: ./AuthService
      dockerfile: Dockerfile
    container_name: authservice-app
    ports:
      - "8082:8082"
    depends_on:
      - authservice-postgres
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://authservice-postgres:5432/${DB_AUTH_SERVICE}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

  orderservice:
    build:
      context: ./OrderService
      dockerfile: Dockerfile
    container_name: orderservice-app
    ports:
      - "8083:8083"
    depends_on:
      - orderservice-postgres
      - kafka
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://orderservice-postgres:5432/${DB_ORDER_SERVICE}"
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SECURITY_JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      USERSERVICE_URL: ${USER_SERVICE_URL}
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  paymentservice:
    build:
      context: ./PaymentService
      dockerfile: Dockerfile
    container_name: paymentservice-app
    ports:
      - "8084:8084"
    depends_on:
      - mongodb
      - kafka
    env_file:
      - .env
    environment:
      MONGO_URL: "mongodb://mongodb:27017/${DB_PAYMENT_SERVICE}"
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092

  kafka:
    image: apache/kafka:4.0.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_NODE_ID=0
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_LOG_DIRS=/var/lib/kafka/data
      - KAFKA_ENABLE_KRAFT=yes
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - kafka_data:/var/lib/kafka/data

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"

  userservice-postgres:
    image: postgres:latest
    container_name: userservice-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_USER_SERVICE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - userservice_db_data:/var/lib/postgresql/data

  authservice-postgres:
    image: postgres:latest
    container_name: authservice-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_AUTH_SERVICE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5435:5432"
    volumes:
      - authservice_db_data:/var/lib/postgresql/data

  orderservice-postgres:
    image: postgres:latest
    container_name: orderservice-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_ORDER_SERVICE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5437:5432"
    volumes:
      - orderservice_db_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.2.1
    container_name: paymentservice_mongo
    restart: always
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: paymentservice
    command: ["mongod", "--bind_ip_all"]

    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  userservice_db_data:
  authservice_db_data:
  orderservice_db_data:
  mongo_data:
  kafka_data: