apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-payment
  labels:
    app: app-payment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-payment
  template:
    metadata:
      name: app-payment
      labels:
        app: app-payment
    spec:
      containers:
        - name: app-payment
          image: voodz/paymentservice:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: system-config
            - secretRef:
                name: system-secrets
          env:
            - name: MONGO_URL
              valueFrom:
                configMapKeyRef:
                  name: system-config
                  key: MONGO_URL
          ports:
            - containerPort: 8084
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5